# Playbook to call multiple roles to configure systems
- name: Configure systems
  hosts: 10.64.27.35m
  become: yes

  tasks:

- name: Call Roles
  hosts: 10.64.27.35
  roles:
   #- hostname
   #- firewalld
   #- ntp-config
   - motd
